# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='puntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.IntegerField()),
                ('facultad', models.CharField(max_length=30)),
                ('concepto', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=1)),
                ('resolucion', models.CharField(max_length=30)),
                ('fecha_res', models.DateField()),
                ('fecha_acta', models.DateField()),
                ('puntos_salariales', models.IntegerField()),
                ('puntos_bonificacion', models.IntegerField()),
            ],
        ),
    ]
