# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0002_auto_20170228_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
