# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0003_auto_20170228_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos',
            name='acta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='fecha_acta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='fecha_res',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='puntos_bonificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='puntos_salariales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
