# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0004_auto_20170228_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntos',
            name='resolucion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
