# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0005_auto_20170228_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos',
            name='enlace_acta',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntos',
            name='enlace_res',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puntos',
            name='facultad',
            field=models.CharField(choices=[('Facultad de Artes - ASAB', 'Facultad de Artes - ASAB'), ('Facultad de Ciencias y Educacion', 'Facultad de Ciencias y Educacion'), ('Facultad de Medio Ambiente y Recursos Naturales', 'Facultad de Medio Ambiente y Recursos Naturales'), ('Facultad de Ingenieria', 'Facultad de Ingenieria'), ('Facultad Tecnologica', 'Facultad Tecnologica')], max_length=70),
        ),
    ]
