# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0002_comisionv2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisionv2',
            old_name='regimen',
            new_name='regimen_comision',
        ),
        migrations.AddField(
            model_name='comisionv2',
            name='regimen_docente',
            field=models.CharField(choices=[('A', ' Acuerdo 003/1973'), ('B', ' Decreto 1279/2002')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='proy_curricular',
            field=models.CharField(max_length=100),
        ),
    ]
