# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0003_auto_20170228_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionv2',
            name='csu_ca_res',
            field=models.CharField(choices=[('A', 'CSU'), ('B', 'CA'), ('C', 'CF'), ('D', 'RECTORIA'), ('E', 'N/D')], max_length=1),
        ),
    ]
