# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0004_auto_20170228_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionv2',
            name='apoyo_bibliografico_otrosi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='fecha_otrosi',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='fecha_titulacion',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='matricula_otrosi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='obj_otrosi',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='responsable_cierre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='salario_RRHH_otrosi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='salario_reemplazo_otrosi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='seguro_medico_otrosi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='soporte_base',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='opt/si/comisiones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='soportes_finales',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='opt/si/comisiones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='tiquetes_otrosi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='valor_otrosi',
            field=models.IntegerField(blank=True),
        ),
    ]
