# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0005_auto_20170228_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionv2',
            name='titulo_otorgado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
