# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0006_auto_20170228_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionv2',
            name='apoyo_bibliografico_otrosi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='fecha_otrosi',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='matricula_otrosi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='salario_RRHH_otrosi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='salario_reemplazo_otrosi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='seguro_medico_otrosi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='tiquetes_otrosi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='valor_otrosi',
            field=models.IntegerField(null=True),
        ),
    ]
