# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0007_auto_20170228_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionv2',
            name='apoyo_bibliografico_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='fecha_otrosi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='fecha_titulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='matricula_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='responsable_cierre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='salario_RRHH_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='salario_reemplazo_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='seguro_medico_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='tiquetes_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='titulo_otorgado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='valor_otrosi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
