# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0008_auto_20170228_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionv2',
            name='soporte_base',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='/opt/si/comisiones/'),
        ),
        migrations.AlterField(
            model_name='comisionv2',
            name='soportes_finales',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='/opt/si/comisiones/'),
        ),
    ]
